---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: display_environments
    inherits: 
    description: 
  fields:
  - query:
      value: environments
  - organisation:
      value: changeme
  - chef_server:
      value: api.opscode.com
  - user_name:
      value: changeme
  - method:
      value: query_chef
