---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - max_owner_vms:
      value: '2'
  - max_group_vms:
      value: '2'
